spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/problemservice
    username: makisekurisu
    password: abcd1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
